services:
  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=${{ shared.PORT }}
      - SPRING_DATASOURCE_URL=${{ shared.AUTH_DB_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ shared.AUTH_DB_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ shared.AUTH_DB_PASSWORD }}
      - JWT_SECRET=${{ shared.JWT_SECRET }}
      - JWT_EXPIRATION=${{ shared.JWT_EXPIRATION }}
      - ALLOWED_ORIGINS=${{ shared.ALLOWED_ORIGINS }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
    restart: always