services:
  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - APP_EMAIL=${{ shared.APP_EMAIL }}
      - DATABASE_NAME=${{ shared.DATABASE_NAME }}
      - DEFAULT_PROFILE_IMAGE=${{ shared.DEFAULT_PROFILE_IMAGE }}
      - ELASTICSEARCH_PASSWORD=${{ shared.ELASTICSEARCH_PASSWORD }}
      - ELASTICSEARCH_URL=${{ shared.ELASTICSEARCH_URL }}
      - ELASTICSEARCH_USERNAME=${{ shared.ELASTICSEARCH_USERNAME }}
      - JWT_SECRET=${{ shared.JWT_SECRET }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      - MAIL_MODIFIED_USERNAME=${{ shared.MAIL_MODIFIED_USERNAME }}
      - MAIL_PASSWORD=${{ shared.MAIL_PASSWORD }}
      - MAIL_REGISTER_CONFIRMATION_LINK=${{ shared.MAIL_REGISTER_CONFIRMATION_LINK }}
      - MONGO_URI=${{ shared.MONGO_URI }}
      - RESET_PASSWORD_LINK=${{ shared.RESET_PASSWORD_LINK }}
    restart: always